const EYELOG_QUESTIONS = [
// ── OPTICS & REFRACTION ───────────────────────────────────────────────────────
{id:'op01',subject:'optics',difficulty:'medium',
stem:'A patient has a spectacle prescription of -3.00 +1.50 x 090. What is the power of this lens in the 180° meridian?',
options:['A. -3.00 D','B. -1.50 D','C. +1.50 D','D. -4.50 D','E. 0.00 D'],
correct:'B',
explanation:'In the 090 meridian the lens power is -3.00 D (sphere). In the 180 meridian the cylinder is added: -3.00 + 1.50 = -1.50 D. Remember: the cylinder axis indicates the meridian where NO cylinder power is added; the full cylinder is added 90° away.',
reference:'BCSC Section 3'},

{id:'op02',subject:'optics',difficulty:'easy',
stem:'A vergence of +2.00 D means light rays are:',
options:['A. Diverging from a point 50 cm away','B. Converging to a point 50 cm away','C. Parallel','D. Diverging from a point 2 m away','E. Converging to a point 2 m away'],
correct:'B',
explanation:'Vergence = 1 / distance (in metres). +2.00 D means converging (+) light headed to a focus 1/2 = 0.50 m (50 cm) ahead.',
reference:'BCSC Section 3'},

{id:'op03',subject:'optics',difficulty:'hard',
stem:'A patient wearing +10.00 D spectacles (vertex distance 14 mm) needs contact lenses. What contact lens power is needed?',
options:['A. +10.00 D','B. +8.70 D','C. +11.54 D','D. +9.00 D','E. +10.50 D'],
correct:'B',
explanation:'Contact lens power = F_spec / (1 - d × F_spec) is for moving away. Correct: moving from spectacle to corneal plane (closer), plus power decreases. F_cl = F/(1+dF) = 10/(1+0.14) = 8.77 ≈ +8.70 D. Use the version where vertex distance correction for plus: contact = spec/(1+d×spec).',
reference:'BCSC Section 3'},

{id:'op04',subject:'optics',difficulty:'medium',
stem:'The nodal point of the reduced schematic eye is located:',
options:['A. At the cornea','B. 17 mm behind the cornea','C. 7 mm behind the cornea','D. At the principal plane of the lens','E. At the retina'],
correct:'C',
explanation:'In the reduced schematic eye, the single refracting surface is placed at the cornea and the nodal point (where rays pass undeviated) is approximately 7 mm behind it — roughly at the posterior lens.',
reference:'BCSC Section 3'},

{id:'op05',subject:'optics',difficulty:'easy',
stem:'A direct ophthalmoscope produces a:',
options:['A. Real, inverted image at 15×','B. Virtual, erect image at approximately 15×','C. Real, erect image at 2×','D. Virtual, inverted image at 15×','E. Real, inverted image at 2×'],
correct:'B',
explanation:'The direct ophthalmoscope creates a virtual, erect (upright), magnified image (~15×). The observer\'s eye and the patient\'s eye together act as a compound microscope.',
reference:'BCSC Section 3'},

{id:'op06',subject:'optics',difficulty:'medium',
stem:'Which of the following best describes the lensometer (lensmeter) measurement principle?',
options:['A. It measures the vergence of light exiting a lens placed in front of a standard eye','B. It uses a Badal optometer: a standard lens creates parallel light from a known vergence target','C. It measures the curvature of each lens surface with a keratometer','D. It uses a Hartmann-Shack wavefront sensor','E. It measures total internal reflection angle to calculate refractive index'],
correct:'B',
explanation:'The lensometer uses a Badal principle: a standard lens (the instrument objective) is placed at its focal length from the unknown lens. A target is moved until the exit light is parallel (neutralized), and the distance moved gives the lens power.',
reference:'BCSC Section 3'},

{id:'op07',subject:'optics',difficulty:'hard',
stem:'A patient with keratoconus achieves 20/20 with a rigid gas-permeable (RGP) contact lens but only 20/100 with spectacles. The MOST likely reason is:',
options:['A. The contact lens corrects higher-order aberrations by creating a new anterior refracting surface','B. The contact lens magnifies the image more than spectacles','C. Spectacles cannot correct more than 10 D of myopia','D. Keratoconus affects only the posterior corneal surface which spectacles cannot address','E. The tear lens formed under an RGP neutralizes irregular astigmatism'],
correct:'E',
explanation:'In keratoconus, irregular astigmatism prevents good spectacle correction. An RGP lens vaults over the irregular cornea; the tear (lacrimal) lens formed between the back of the RGP and the cone fills in the irregularity, effectively replacing the irregular corneal surface with a smooth spherical interface. This is the primary mechanism, not higher-order aberration correction per se.',
reference:'BCSC Section 3'},

{id:'op08',subject:'optics',difficulty:'medium',
stem:'A +5.00 D thin lens has its object placed 25 cm in front of it. Where is the image?',
options:['A. 50 cm behind the lens','B. 100 cm behind the lens','C. 25 cm in front of the lens (virtual)','D. Infinity','E. 33 cm behind the lens'],
correct:'B',
explanation:'Using 1/v - 1/u = P: object at u = -0.25 m, P = +5 D, f = 0.20 m. 1/v = 1/f + 1/u = 5 + (-4) = 1. So v = 1 m = 100 cm. Object at 25 cm from a +5 D lens (f=20 cm): since object is beyond f, image is real and at 100 cm behind the lens.',
reference:'BCSC Section 3'},

// ── CATARACT & LENS ───────────────────────────────────────────────────────────
{id:'ca01',subject:'cataract',difficulty:'medium',
stem:'A 68-year-old diabetic undergoes uncomplicated phacoemulsification. Which intraocular lens (IOL) feature is MOST important to reduce posterior capsule opacification (PCO)?',
options:['A. Hydrophilic acrylic material','B. Square posterior optic edge','C. Large optic diameter (>7 mm)','D. Blue-light filtering chromophore','E. Plate haptic design'],
correct:'B',
explanation:'The square (sharp/truncated) posterior optic edge creates a physical barrier at the optic-capsule interface that prevents lens epithelial cell migration onto the posterior capsule — the main mechanism of PCO. This is the single most important design feature for PCO reduction.',
reference:'BCSC Section 11'},

{id:'ca02',subject:'cataract',difficulty:'easy',
stem:'During phacoemulsification, a posterior capsule tear is noted after hydrodissection but before nuclear disassembly. The BEST next step is:',
options:['A. Convert immediately to ECCE','B. Inject viscoelastic behind the nucleus to tamponade the tear, then proceed carefully','C. Place a capsular tension ring','D. Abandon the case and reschedule','E. Continue phaco normally as the tear is small'],
correct:'B',
explanation:'Injecting a dispersive viscoelastic (e.g., Viscoat) behind the nuclear fragment supports the vitreous face and prevents extension of the tear. The surgeon can then proceed with careful phacoemulsification, ideally converting to a slower, lower-vacuum technique. Immediate ECCE conversion is an option if the tear is large, but controlled use of viscoelastic first is preferred.',
reference:'BCSC Section 11'},

{id:'ca03',subject:'cataract',difficulty:'hard',
stem:'Which formula is MOST accurate for short eyes (axial length <22 mm)?',
options:['A. SRK/T','B. Holladay 1','C. Barrett Universal II','D. SRK II','E. Hoffer Q'],
correct:'C',
explanation:'For short eyes (<22 mm), modern vergence formulas like Barrett Universal II, Hill-RBF, and Kane outperform older generation formulas. Hoffer Q was traditionally preferred for short eyes over SRK/T, but Barrett Universal II consistently shows lowest mean prediction error across all axial lengths including short eyes in recent large comparative studies.',
reference:'BCSC Section 11'},

{id:'ca04',subject:'cataract',difficulty:'medium',
stem:'A patient reports monocular diplopia after cataract surgery. Slit lamp shows the IOL optic straddling the anterior capsulorrhexis edge. The MOST likely cause of the diplopia is:',
options:['A. Induced irregular astigmatism','B. Edge glare from the haptic','C. Dysphotopsia from light passing around the IOL edge','D. Capsular contraction syndrome','E. Decentration causing prismatic effect'],
correct:'C',
explanation:'When the IOL optic edge is not fully covered by the capsulorrhexis (i.e., IOL-in-the-bag with edge exposed), light can difract around the IOL edge causing dysphotopsia — positive (bright arcs/flashes) or negative (dark arc in temporal field). Straddling the rhexis edge classically produces edge-related dysphotopsia.',
reference:'BCSC Section 11'},

{id:'ca05',subject:'cataract',difficulty:'medium',
stem:'The "no-reflow" phenomenon after capsular tension ring (CTR) placement refers to:',
options:['A. Failure of the capsule to re-expand after viscoelastic removal','B. Occlusion of the ciliary body blood supply during ring placement','C. Iris ischemia after prolonged pupil stretching','D. Choroidal non-perfusion seen after hypotony during vitreous loss','E. Fibrin formation blocking the trabecular meshwork postoperatively'],
correct:'A',
explanation:'No-reflow in cataract surgery context refers to failure of the posterior capsule to re-expand and come into contact with the IOL after removal of viscoelastic — typically seen with a CTR in the bag and improperly formed posterior capsule.',
reference:'BCSC Section 11'},

{id:'ca06',subject:'cataract',difficulty:'easy',
stem:'Posterior polar cataract is associated with increased risk of:',
options:['A. Zonular dialysis','B. Posterior capsule rupture during hydrodissection','C. Corneal decompensation','D. Suprachoroidal hemorrhage','E. Iris prolapse'],
correct:'B',
explanation:'Posterior polar cataracts have a pre-existing defect or thinning of the posterior capsule at the polar opacity. Hydrodissection can cause a fluid wave that ruptures this weakened capsule. The key surgical modification is to perform hydrodelineation instead, and use extra care or skip hydrodissection entirely.',
reference:'BCSC Section 11'},

{id:'ca07',subject:'cataract',difficulty:'hard',
stem:'A patient with a history of LASIK for myopia now needs cataract surgery. Which IOL calculation adjustment is MOST appropriate?',
options:['A. Add +0.50 D to the standard IOL power','B. Use the Clinical History Method or a corneal bypass formula','C. Rely on automated keratometry alone','D. Use the thinnest corneal zone for keratometry','E. Increase the A-constant by 1.0'],
correct:'B',
explanation:'Post-refractive surgery eyes have altered anterior corneal curvature. Standard keratometry over-estimates corneal power (using a fixed index of refraction that no longer applies). The Clinical History Method (adjusting K with pre-LASIK data), Haigis-L, Barrett True-K, or the ASCRS post-refractive calculator are preferred. Never rely on standard automated keratometry alone.',
reference:'BCSC Section 11'},

{id:'ca08',subject:'cataract',difficulty:'medium',
stem:'Floppy iris syndrome (IFIS) is most commonly associated with which medication?',
options:['A. Tamsulosin (Flomax)','B. Metoprolol','C. Aspirin','D. Amlodipine','E. Sildenafil'],
correct:'A',
explanation:'Intraoperative floppy iris syndrome (IFIS) is strongly associated with systemic alpha-1-adrenergic antagonists, especially tamsulosin (used for benign prostatic hyperplasia). The iris dilator muscle is blocked, leading to intraoperative iris billowing, prolapse, and progressive miosis. Surgeons must be warned preoperatively — the drug does not need to be stopped but technique modification (iris hooks, Malyugin ring, intracameral phenylephrine, low-flow phaco) is needed.',
reference:'BCSC Section 11'},

{id:'ca09',subject:'cataract',difficulty:'hard',
stem:'In which situation is a toric IOL MOST likely to under-correct the astigmatism despite accurate preoperative planning?',
options:['A. Posterior corneal astigmatism exceeding +0.5 D in magnitude','B. With-the-rule astigmatism in a young patient','C. Posterior corneal astigmatism not accounted for in the calculation','D. IOL rotation of less than 5 degrees','E. Axial length >25 mm'],
correct:'C',
explanation:'The posterior cornea contributes approximately 0.3 D of against-the-rule astigmatism on average. Keratometers and topographers measure ANTERIOR corneal curvature only. If posterior corneal astigmatism is not accounted for (using Barrett Toric, Abulafia-Koch formula, or direct measurement by Scheimpflug/OCT), a toric IOL calculated from anterior K values alone will be systematically miscalculated.',
reference:'BCSC Section 11'},

// ── CORNEA & EXTERNAL DISEASE ─────────────────────────────────────────────────
{id:'co01',subject:'cornea',difficulty:'easy',
stem:'A 25-year-old contact lens wearer presents with a central corneal ulcer, hypopyon, and severe pain. Gram stain of the scraping shows gram-negative rods. The MOST likely organism is:',
options:['A. Staphylococcus aureus','B. Streptococcus pneumoniae','C. Pseudomonas aeruginosa','D. Acanthamoeba','E. Fusarium solani'],
correct:'C',
explanation:'Pseudomonas aeruginosa is the most common gram-negative rod causing bacterial keratitis, especially in contact lens wearers. It produces rapid, aggressive stromal necrosis with a characteristic "ground-glass" opacification and mucopurulent discharge. Treatment: intensive topical fluoroquinolone (ciprofloxacin or moxifloxacin).',
reference:'BCSC Section 8'},

{id:'co02',subject:'cornea',difficulty:'medium',
stem:'Lattice corneal dystrophy type I (Biber-Haab-Dimmer) is caused by mutations in which gene?',
options:['A. TGFBI (transforming growth factor beta-induced)','B. SLC4A11','C. ZEB1','D. VSX1','E. COL8A2'],
correct:'A',
explanation:'TGFBI (formerly BIGH3) mutations cause multiple corneal stromal dystrophies depending on the specific mutation: Granular type I (R555W), Granular type II/Avellino (R124H), Lattice type I (R124C), and Reis-Bucklers (R124L). All are autosomal dominant. SLC4A11 causes CHED. ZEB1 causes Posterior polymorphous and CHED2. VSX1 causes Keratoconus. COL8A2 causes FECD.',
reference:'BCSC Section 8'},

{id:'co03',subject:'cornea',difficulty:'medium',
stem:'A patient with recurrent corneal erosion syndrome reports waking at night with severe pain and tearing. The FIRST-LINE treatment after an acute episode has resolved is:',
options:['A. Phototherapeutic keratectomy (PTK)','B. Anterior stromal puncture','C. Hypertonic saline drops and lubricating ointment at bedtime','D. Bandage contact lens permanently','E. Corneal scraping and debridement'],
correct:'C',
explanation:'First-line management for recurrent corneal erosion syndrome (RCES) is lubricating ointment at bedtime and hypertonic saline (5% NaCl) drops during the day to reduce epithelial edema and strengthen epithelial adhesion. If this fails after 3-6 months, procedural options include anterior stromal puncture (for non-visual axis erosions), diamond burr polishing, or PTK.',
reference:'BCSC Section 8'},

{id:'co04',subject:'cornea',difficulty:'hard',
stem:'Fuchs endothelial corneal dystrophy (FECD) most commonly results from trinucleotide repeat expansion in which gene?',
options:['A. COL8A2','B. TCF4 (transcription factor 4)','C. SLC4A11','D. LOXHD1','E. ZEB1'],
correct:'B',
explanation:'The most common genetic cause of late-onset FECD (>95% of cases) is a CTG trinucleotide repeat expansion in intron 2 of TCF4. This creates nuclear RNA foci that sequester splicing factors. Early-onset FECD is caused by COL8A2 mutations (autosomal dominant). ZEB1 mutations cause posterior polymorphous dystrophy and CHED2.',
reference:'BCSC Section 8'},

{id:'co05',subject:'cornea',difficulty:'easy',
stem:'Acanthamoeba keratitis is strongly associated with which risk factor?',
options:['A. HIV/AIDS','B. Soft contact lens wear with tap water exposure','C. Herpes simplex virus keratitis','D. Dry eye disease','E. Post-refractive surgery'],
correct:'B',
explanation:'Acanthamoeba keratitis is overwhelmingly associated with contact lens wear, particularly exposure to contaminated water (tap water, swimming pools, hot tubs). The classic presentation is severe pain out of proportion to slit-lamp findings and a ring-shaped stromal infiltrate. Diagnosis: confocal microscopy, culture on non-nutrient agar with E. coli overlay.',
reference:'BCSC Section 8'},

{id:'co06',subject:'cornea',difficulty:'medium',
stem:'Penetrating keratoplasty (PK) versus Descemet membrane endothelial keratoplasty (DMEK) for Fuchs dystrophy: which statement is MOST accurate?',
options:['A. PK provides faster visual recovery','B. DMEK has higher graft rejection rates than PK','C. DMEK provides better visual acuity outcomes and lower rejection rates','D. DMEK is preferred for eyes with significant anterior stromal scarring','E. PK and DMEK have equivalent refractive predictability'],
correct:'C',
explanation:'DMEK replaces only the diseased Descemet membrane and endothelium (the pathological layers in FECD). Advantages over PK: faster visual recovery (weeks vs months-years), better final BCVA (often 20/20+), dramatically lower rejection rates (~1% vs ~20%), no suture-related issues, less induced astigmatism. DMEK is NOT appropriate for anterior stromal disease; it only corrects endothelial dysfunction.',
reference:'BCSC Section 8'},

{id:'co07',subject:'cornea',difficulty:'hard',
stem:'A 35-year-old with progressive keratoconus (Kmax 58 D, pachymetry 440 um) requests corneal collagen cross-linking (CXL). Which contraindication applies?',
options:['A. Age over 30','B. Pachymetry less than 400 um at the thinnest point','C. Kmax greater than 55 D','D. Prior LASIK','E. Contact lens wear'],
correct:'B',
explanation:'The minimum corneal thickness for standard (Dresden protocol) CXL is 400 um AFTER epithelial removal, as the UV-A light must not reach the endothelium (which would be damaged at depths beyond ~300 um of stroma). At 440 um total, after removing ~50 um of epithelium, the residual stroma would be ~390 um — below the 400 um threshold. Accelerated or modified protocols (hypotonic riboflavin to swell the cornea) may be used in thin corneas.',
reference:'BCSC Section 8'},

{id:'co08',subject:'cornea',difficulty:'medium',
stem:'Herpes zoster ophthalmicus (HZO) involves the ophthalmic division of CN V. The Hutchinson sign (vesicles on the tip of the nose) predicts involvement of:',
options:['A. The lacrimal nerve','B. The frontal nerve','C. The nasociliary nerve','D. The supraorbital nerve','E. The infraorbital nerve'],
correct:'C',
explanation:'The nasociliary branch of V1 innervates both the tip of the nose (via the external nasal nerve) and the globe (via the long ciliary nerves). Hutchinson sign indicates nasociliary involvement, predicting a 76% risk of ocular involvement in HZO. The lacrimal nerve innervates the lacrimal gland and lateral upper lid. The frontal nerve innervates the forehead.',
reference:'BCSC Section 8'},

// ── GLAUCOMA ──────────────────────────────────────────────────────────────────
{id:'gl01',subject:'glaucoma',difficulty:'easy',
stem:'The normal range of central corneal thickness (CCT) is approximately:',
options:['A. 400-450 um','B. 500-560 um','C. 580-620 um','D. 450-480 um','E. 560-600 um'],
correct:'B',
explanation:'Average CCT is approximately 540-545 um with a normal range of ~500-560 um. CCT significantly affects Goldmann applanation tonometry readings: thicker corneas give falsely HIGH readings; thinner corneas give falsely LOW readings. The Ocular Hypertension Treatment Study showed thin CCT is an independent risk factor for glaucoma conversion.',
reference:'BCSC Section 10'},

{id:'gl02',subject:'glaucoma',difficulty:'medium',
stem:'A patient has a cup-to-disc ratio of 0.8 with inferior notching and an arcuate scotoma on Humphrey visual field (24-2). IOP is 14 mmHg on two occasions. The MOST appropriate diagnosis is:',
options:['A. Physiologic cupping','B. Ocular hypertension','C. Normal-tension glaucoma','D. Angle-closure glaucoma suspect','E. Non-glaucomatous optic neuropathy'],
correct:'C',
explanation:'Normal-tension glaucoma (NTG) is defined as glaucomatous optic neuropathy (structural loss: notching, thinning) with corresponding functional loss (VF defect) in the absence of elevated IOP (21 mmHg or less). IOP of 14 mmHg on two occasions meets this criterion. NTG is associated with vasospasm, systemic hypotension, Flammer syndrome, and obstructive sleep apnea.',
reference:'BCSC Section 10'},

{id:'gl03',subject:'glaucoma',difficulty:'hard',
stem:'Which glaucoma medication is CONTRAINDICATED in a patient with sickle cell disease?',
options:['A. Latanoprost','B. Timolol','C. Dorzolamide','D. Brimonidine','E. Pilocarpine'],
correct:'C',
explanation:'Carbonic anhydrase inhibitors (dorzolamide, brinzolamide, acetazolamide) lower aqueous pH and bicarbonate, which can cause sickling of red blood cells in the anterior chamber and trabecular meshwork, potentially worsening IOP and causing vascular complications. Systemic CAIs are also contraindicated. Timolol is the safest option.',
reference:'BCSC Section 10'},

{id:'gl04',subject:'glaucoma',difficulty:'medium',
stem:'The Tube Versus Trabeculectomy (TVT) study showed that at 5 years:',
options:['A. Trabeculectomy had significantly lower IOP than tube shunt','B. Tube shunts had similar IOP control with fewer failures than trabeculectomy','C. Tube shunts had higher rates of hypotony maculopathy','D. Trabeculectomy had fewer late complications than tube shunts','E. Both procedures had similar failure rates and similar IOP'],
correct:'B',
explanation:'The TVT study (5-year results): tube shunts (Baerveldt 350) and trabeculectomy with MMC had similar mean IOP (~14 mmHg). However, trabeculectomy had a higher cumulative failure rate (46.9%) vs tube shunts (29.8%). Trabeculectomy also had more early hypotony and vision-threatening complications. Tubes had more late complications (corneal, erosion).',
reference:'BCSC Section 10'},

{id:'gl05',subject:'glaucoma',difficulty:'easy',
stem:'Pigment dispersion syndrome (PDS) is characterized by all of the following EXCEPT:',
options:['A. Krukenberg spindle','B. Sampaolesi line anterior to Schwalbe line','C. Radial iris transillumination defects','D. Dense trabecular pigmentation','E. Backward bowing of the iris'],
correct:'B',
explanation:'Sampaolesi line (anterior to Schwalbe line) is seen in exfoliation syndrome/pseudoexfoliation glaucoma, not PDS. PDS features: Krukenberg spindle (pigment on corneal endothelium, vertical spindle-shaped), radial/spoke-wheel iris transillumination defects from posterior iris rubbing the lens zonules, dense trabecular meshwork pigmentation (360 degrees, most dense inferiorly), and posterior bowing (concave) of the iris due to reverse pupillary block.',
reference:'BCSC Section 10'},

{id:'gl06',subject:'glaucoma',difficulty:'medium',
stem:'A bleb-related endophthalmitis after trabeculectomy is MOST commonly caused by:',
options:['A. Staphylococcus aureus','B. Streptococcus species','C. Gram-negative organisms','D. Candida species','E. Haemophilus influenzae'],
correct:'B',
explanation:'Late bleb-related endophthalmitis (blebitis/endophthalmitis) is most commonly caused by streptococcal species (Streptococcus pneumoniae, viridans streptococci), which account for ~20-30% of cases. Staphylococcus epidermidis and Haemophilus influenzae are also common. These are more virulent and have worse visual prognosis than typical post-cataract endophthalmitis (which is predominantly S. epidermidis).',
reference:'BCSC Section 10'},

{id:'gl07',subject:'glaucoma',difficulty:'hard',
stem:'In selective laser trabeculoplasty (SLT), the target chromophore is:',
options:['A. Water in trabecular cells','B. Melanin in pigmented trabecular meshwork cells','C. Hemoglobin in trabecular blood vessels','D. Collagen in the scleral spur','E. Lipofuscin in juxtacanalicular cells'],
correct:'B',
explanation:'SLT uses a Q-switched, frequency-doubled Nd:YAG laser (532 nm green) that selectively targets melanin-containing cells in the trabecular meshwork. The pulse duration (3 ns) is shorter than the thermal relaxation time of trabecular cells, so only pigmented cells are disrupted without collateral thermal damage to adjacent tissue (selective photothermolysis principle). This allows SLT to be safely repeated.',
reference:'BCSC Section 10'},

{id:'gl08',subject:'glaucoma',difficulty:'medium',
stem:'A patient with exfoliation glaucoma is scheduled for cataract surgery. The surgeon should anticipate:',
options:['A. Larger-than-average pupil dilation','B. Increased risk of zonular dialysis and vitreous loss','C. Lower risk of posterior capsule opacification','D. More accurate IOL power calculation','E. Reduced risk of postoperative IOP spike'],
correct:'B',
explanation:'Pseudoexfoliation (PXF) material deposits on and weakens the zonules. Zonular fragility increases the risk of capsular-zonular dialysis, vitreous prolapse, and dropped nucleus. Other concerns: poor pupil dilation (PXF material on iris sphincter), risk of capsular contraction syndrome, and IOP spikes post-surgery. A capsular tension ring (CTR) should be available and used liberally if zonular weakness is noted.',
reference:'BCSC Section 10'},

// ── RETINA & VITREOUS ─────────────────────────────────────────────────────────
{id:'re01',subject:'retina',difficulty:'easy',
stem:'A 65-year-old presents with sudden onset of painless vision loss, described as a "curtain" coming across the vision. The MOST urgent evaluation is for:',
options:['A. Central retinal artery occlusion','B. Rhegmatogenous retinal detachment','C. Vitreous hemorrhage','D. Central serous chorioretinopathy','E. Age-related macular degeneration'],
correct:'B',
explanation:'A "curtain" or "shadow" coming across the visual field is the classic description of a rhegmatogenous retinal detachment (RRD) with the advancing edge of detached retina causing a corresponding visual field defect. This is a surgical emergency. CRAO causes sudden, painless, complete or near-complete vision loss (no curtain description). Vitreous hemorrhage causes floaters/red haze.',
reference:'BCSC Section 12'},

{id:'re02',subject:'retina',difficulty:'medium',
stem:'Anti-VEGF therapy is the standard of care for which condition?',
options:['A. Non-proliferative diabetic retinopathy without macular edema','B. Neovascular (wet) age-related macular degeneration','C. Non-exudative (dry) AMD with drusen only','D. Epiretinal membrane','E. Vitreomacular traction syndrome'],
correct:'B',
explanation:'Anti-VEGF agents (ranibizumab, bevacizumab, aflibercept, brolucizumab, faricimab) are the standard of care for neovascular (wet) AMD, significantly improving visual outcomes compared to natural history. They are also used for diabetic macular edema (DME), macular edema from CRVO/BRVO. Non-exudative AMD has no proven treatment (complements/AREDS2 for intermediate). ERM and VMT are treated surgically (vitrectomy).',
reference:'BCSC Section 12'},

{id:'re03',subject:'retina',difficulty:'hard',
stem:'The HARBOR trial compared monthly vs. as-needed (PRN) ranibizumab for neovascular AMD. The main finding was:',
options:['A. PRN dosing was superior to monthly in visual acuity outcomes','B. Monthly and PRN dosing had equivalent visual outcomes; monthly required fewer injections','C. Monthly dosing showed superior visual outcomes; PRN was non-inferior only in the 2.0 mg arm','D. PRN dosing was associated with more geographic atrophy','E. Monthly dosing achieved better anatomic outcomes with similar visual acuity at 2 years'],
correct:'C',
explanation:'HARBOR compared ranibizumab 0.5 mg monthly vs PRN and 2.0 mg monthly vs PRN. Monthly dosing (both doses) achieved superior mean VA gains vs PRN at 24 months. The 2.0 mg PRN group was non-inferior to 0.5 mg monthly. This suggests monthly dosing is optimal but high-dose PRN may approximate it. This contrasts with CATT which showed bevacizumab PRN was not inferior to ranibizumab monthly.',
reference:'BCSC Section 12'},

{id:'re04',subject:'retina',difficulty:'medium',
stem:'In a patient with branch retinal artery occlusion (BRAO), the visual field defect is:',
options:['A. Central scotoma','B. Altitudinal defect respecting the horizontal meridian','C. Sectoral defect corresponding to the affected retinal territory','D. Bitemporal hemianopia','E. Homonymous hemianopia'],
correct:'C',
explanation:'BRAO causes infarction of the retinal territory supplied by the affected branch. This produces a sectoral (wedge-shaped) visual field defect corresponding to that retinal area. The superior temporal branch is most commonly affected (possibly due to embolus pathway), causing an inferior nasal sector defect. Altitudinal defects (respecting the horizontal meridian) are more typical of anterior ischemic optic neuropathy (AION).',
reference:'BCSC Section 12'},

{id:'re05',subject:'retina',difficulty:'easy',
stem:'Diabetic macular edema (DME) is defined as retinal thickening or hard exudates within:',
options:['A. 1 disc diameter of the fovea','B. 500 um of the fovea center','C. 1 disc diameter of the optic disc','D. 2 disc diameters of the fovea','E. The foveal avascular zone only'],
correct:'A',
explanation:'Clinically significant macular edema (CSME) — the classic definition — includes retinal thickening within 500 um of the fovea center, hard exudates within 500 um of the fovea with adjacent thickening, or retinal thickening of 1 disc area or more within 1 disc diameter of the fovea. For practical purposes, DME/CSME involves changes within 1 disc diameter of the fovea.',
reference:'BCSC Section 12'},

{id:'re06',subject:'retina',difficulty:'hard',
stem:'A patient with proliferative diabetic retinopathy develops sudden visual loss with an ultrasound showing a tractional retinal detachment involving the macula. The BEST surgical approach is:',
options:['A. Scleral buckle only','B. Panretinal photocoagulation to regress neovascularization before surgery','C. Pars plana vitrectomy with membrane peeling','D. Anti-VEGF injection alone','E. Observe for 6 weeks for spontaneous resolution'],
correct:'C',
explanation:'Tractional retinal detachment (TRD) involving the macula is an indication for pars plana vitrectomy (PPV) with careful membrane dissection (delamination/segmentation) to relieve traction. Anti-VEGF 3-7 days pre-op can reduce bleeding and facilitate membrane peeling (adjunctive, not definitive). Scleral buckle is not appropriate for TRD (no break to close). PRP may worsen TRD by causing fibrovascular contraction.',
reference:'BCSC Section 12'},

{id:'re07',subject:'retina',difficulty:'medium',
stem:'Vogt-Koyanagi-Harada (VKH) disease in the acute uveitic phase classically shows on FA/ICGA:',
options:['A. Multifocal chorioretinitis with "punched-out" lesions','B. Disc hyperfluorescence and multifocal pinpoint subretinal leakage in a "starry sky" pattern','C. Frosted branch angiitis','D. Choroidal ischemia with watershed zone infarction','E. Macular star with disc edema'],
correct:'B',
explanation:'Acute VKH shows bilateral exudative retinal detachments. FA demonstrates disc leakage, multifocal pinpoint RPE leaks at the level of choroidal stroma giving a "starry sky" appearance, and pooling in subretinal space. ICGA shows hypofluorescent dark dots (choroidal inflammation). Delayed VKH shows "sunset glow" fundus (depigmentation), Dalen-Fuchs nodules, perilimbal vitiligo (Sugiura sign).',
reference:'BCSC Section 9/12'},

{id:'re08',subject:'retina',difficulty:'medium',
stem:'Which of the following is MOST characteristic of retinitis pigmentosa (RP)?',
options:['A. Central scotoma and color vision loss early','B. Night blindness and peripheral visual field loss with bone spicule pigmentation','C. Rapid progression to blindness within 5 years','D. Autosomal dominant inheritance only','E. Normal electroretinogram (ERG) until late stages'],
correct:'B',
explanation:'RP classically presents with nyctalopia (night blindness) from early rod photoreceptor loss, progressing to peripheral visual field constriction ("tunnel vision") and bone spicule pigment migration. Central vision is relatively preserved until late. ERG shows reduced rod and cone responses early. Inheritance: autosomal dominant (most common, ~30-40%), autosomal recessive (~50-60%), X-linked (most severe).',
reference:'BCSC Section 12'},

// ── OCULOPLASTICS & ORBIT ─────────────────────────────────────────────────────
{id:'pl01',subject:'oculoplastics',difficulty:'medium',
stem:'A 55-year-old presents with unilateral proptosis, resistance to retropulsion, and an afferent pupillary defect. CT shows an infiltrative orbital mass with bone erosion. The MOST likely diagnosis is:',
options:['A. Cavernous hemangioma','B. Thyroid eye disease','C. Orbital lymphoma','D. Metastatic carcinoma','E. Idiopathic orbital inflammatory syndrome (orbital pseudotumor)'],
correct:'D',
explanation:'Bone erosion on CT is a red flag for malignancy. Metastatic carcinoma (breast in women, prostate in men most commonly) can cause osteolytic or osteoblastic bone changes. Lymphoma typically does NOT erode bone. Cavernous hemangioma is well-circumscribed without bone changes. Thyroid eye disease shows muscle enlargement but no bone erosion. APD indicates optic nerve compression.',
reference:'BCSC Section 7'},

{id:'pl02',subject:'oculoplastics',difficulty:'easy',
stem:'The most common benign orbital tumor in adults is:',
options:['A. Rhabdomyosarcoma','B. Lymphoma','C. Cavernous venous malformation (cavernous hemangioma)','D. Dermoid cyst','E. Neurofibroma'],
correct:'C',
explanation:'Cavernous venous malformation (historically called cavernous hemangioma) is the most common benign orbital tumor in adults. It presents as slow progressive painless proptosis in middle-aged women. CT shows a well-circumscribed, homogeneous intraconal mass with enhancement. It does NOT require treatment unless causing compressive optic neuropathy or significant cosmetic deformity. Rhabdomyosarcoma is the most common primary orbital malignancy in children.',
reference:'BCSC Section 7'},

{id:'pl03',subject:'oculoplastics',difficulty:'medium',
stem:'In thyroid eye disease (TED), the extraocular muscle affected MOST commonly (and earliest) is the:',
options:['A. Superior rectus','B. Lateral rectus','C. Superior oblique','D. Inferior rectus','E. Medial rectus'],
correct:'D',
explanation:'The inferior rectus is the most commonly affected muscle in TED, causing hypotropia and restriction of upgaze (due to fibrosis). Mnemonic: "I\'M SLow" — Inferior, Medial, Superior, Lateral (in descending order of frequency). The inferior rectus restriction can also cause an abnormal head position and diplopia worse in upgaze.',
reference:'BCSC Section 7'},

{id:'pl04',subject:'oculoplastics',difficulty:'hard',
stem:'The clinical activity score (CAS) in thyroid eye disease is used to:',
options:['A. Determine the severity of proptosis','B. Predict visual loss risk from compressive optic neuropathy','C. Assess inflammatory activity to guide immunosuppressive treatment timing','D. Measure diplopia severity for surgical planning','E. Determine risk of corneal exposure'],
correct:'C',
explanation:'The Clinical Activity Score (CAS) uses 7 parameters (pain at rest, pain on eye movement, redness of eyelids, redness of conjunctiva, chemosis, swollen caruncle/plica, lid edema) to score inflammatory activity 0-7. A CAS of 3 or more out of 7 suggests active disease that is likely to respond to immunosuppression (IV methylprednisolone, teprotumumab). CAS guides WHEN to treat with immunosuppression, not the severity of structural damage.',
reference:'BCSC Section 7'},

{id:'pl05',subject:'oculoplastics',difficulty:'medium',
stem:'A biopsy of an eyelid lesion shows nests of basaloid cells with peripheral palisading and retraction artifact. The diagnosis is:',
options:['A. Squamous cell carcinoma','B. Sebaceous gland carcinoma','C. Basal cell carcinoma','D. Merkel cell carcinoma','E. Lymphoma'],
correct:'C',
explanation:'Basal cell carcinoma (BCC) is the most common eyelid malignancy (>90%). Histology shows nests or cords of basaloid cells with peripheral palisading (nuclei aligned at the periphery of nests) and retraction artifact (stromal retraction around nests). It most commonly occurs on the lower eyelid. Treatment: surgical excision with Mohs micrographic surgery for eyelid lesions. BCC metastasizes very rarely.',
reference:'BCSC Section 7'},

// ── PEDIATRIC OPHTHALMOLOGY & STRABISMUS ──────────────────────────────────────
{id:'pe01',subject:'pediatrics',difficulty:'easy',
stem:'A 3-year-old presents with a constant right esotropia of 30 prism diopters. Cycloplegic refraction shows +5.00 D OU. The FIRST treatment should be:',
options:['A. Immediate surgical correction of the esotropia','B. Full cycloplegic spectacle correction','C. Patching of the left eye for amblyopia','D. Botulinum toxin injection into the right medial rectus','E. Prism therapy'],
correct:'B',
explanation:'This is accommodative esotropia. The high hyperopia (+5.00 D) drives excess accommodative convergence, causing the esotropia. Treatment: FULL cycloplegic spectacle correction first. Once proper glasses are worn, the esotropia may fully or partially resolve. If residual deviation remains after 3-6 months of glasses wear, surgery addresses the non-accommodative component. Amblyopia treatment is concurrent if present.',
reference:'BCSC Section 6'},

{id:'pe02',subject:'pediatrics',difficulty:'medium',
stem:'The AC/A ratio is elevated in which type of esotropia?',
options:['A. Congenital (infantile) esotropia','B. Sensory esotropia','C. Basic esotropia','D. Convergence excess esotropia','E. Divergence insufficiency'],
correct:'D',
explanation:'Convergence excess esotropia has a high AC/A ratio — the esotropia is significantly larger at near than at distance. Treatment: bifocals (executive style, +3.00 D add) to reduce the accommodative convergence at near. Alternatively, miotics (echothiophate). Infantile esotropia has a normal or variable AC/A. The AC/A ratio = (esotropia at near - esotropia at far in PD) / accommodation in diopters.',
reference:'BCSC Section 6'},

{id:'pe03',subject:'pediatrics',difficulty:'hard',
stem:'A 6-month-old is found to have leukocoria in the right eye. B-scan ultrasound shows calcification. The MOST likely diagnosis is:',
options:['A. Cataract','B. Retinopathy of prematurity','C. Retinoblastoma','D. Persistent fetal vasculature (PFV)','E. Coats disease'],
correct:'C',
explanation:'Leukocoria with calcification (high-reflectivity foci on B-scan / calcification on CT) in a child under 3 is retinoblastoma until proven otherwise. Retinoblastoma is the most common primary intraocular malignancy in children. Calcification within the mass on ultrasound or CT is pathognomonic. PFV (persistent fetal vasculature) also causes leukocoria but is typically unilateral, has a stalk, and microphthalmia without calcification.',
reference:'BCSC Section 6'},

{id:'pe04',subject:'pediatrics',difficulty:'medium',
stem:'Brown syndrome is characterized by:',
options:['A. Inability to adduct in all fields of gaze','B. Limitation of elevation in adduction due to a tight superior oblique tendon sheath','C. Esotropia that is larger in upgaze than downgaze','D. Alternating hypertropia in primary position','E. Downward and inward deviation of the affected eye'],
correct:'B',
explanation:'Brown syndrome is caused by a tight or thickened superior oblique tendon-trochlear complex, restricting the inferior oblique\'s elevation in adduction (which it opposes). Key features: restricted elevation in adduction, normal or near-normal elevation in abduction, no superior oblique overaction, widening of the palpebral fissure on attempted adduction-elevation, and a "click" sometimes palpable at the trochlea.',
reference:'BCSC Section 6'},

{id:'pe05',subject:'pediatrics',difficulty:'easy',
stem:'The critical period for amblyopia treatment (patching) is:',
options:['A. Birth to 6 months','B. Birth to 3 years','C. Up to approximately 7-9 years','D. Up to 18 years','E. Adults can develop amblyopia as readily as children'],
correct:'C',
explanation:'The visual cortex has a critical period of plasticity during which visual deprivation can cause amblyopia and during which patching/treatment can reverse it. This period extends approximately to age 7-9 years (end of the sensitive period). After this, amblyopia treatment becomes less effective. However, some residual plasticity persists into early teenage years, and patching can still help up to about age 12-17 with decreasing efficacy.',
reference:'BCSC Section 6'},

// ── NEURO-OPHTHALMOLOGY ───────────────────────────────────────────────────────
{id:'ne01',subject:'neuro',difficulty:'medium',
stem:'A 35-year-old woman presents with painful monocular vision loss over 3 days, a relative afferent pupillary defect (RAPD), dyschromatopsia, and a cecocentral scotoma. MRI shows gadolinium enhancement of the optic nerve. The MOST likely diagnosis is:',
options:['A. Anterior ischemic optic neuropathy (AION)','B. Compressive optic neuropathy','C. Demyelinating optic neuritis','D. Leber hereditary optic neuropathy','E. Toxic/nutritional optic neuropathy'],
correct:'C',
explanation:'This is the classic presentation of demyelinating optic neuritis: young woman, painful eye movement, subacute vision loss, RAPD, color vision loss disproportionate to acuity, and MRI optic nerve enhancement. It is frequently associated with multiple sclerosis. The Optic Neuritis Treatment Trial (ONTT) showed IV methylprednisolone speeds recovery but does not improve final vision. AION is typically painless, older patients, altitudinal defect.',
reference:'BCSC Section 5'},

{id:'ne02',subject:'neuro',difficulty:'easy',
stem:'A patient with a right third nerve palsy has a completely blown pupil (dilated, non-reactive) and ptosis. The MOST URGENT next step is:',
options:['A. MRI with contrast of the orbits','B. CT angiography of the head (CTA) to rule out posterior communicating artery aneurysm','C. Thyroid function tests','D. Blood pressure measurement','E. Fasting blood glucose'],
correct:'B',
explanation:'A pupil-involving CN III palsy is a posterior communicating artery (PComm) aneurysm until proven otherwise. The aneurysm compresses the superficial pupillomotor fibers traveling on the outside of CN III. This is a neurosurgical emergency. CTA or MRA should be obtained immediately. Pupil-sparing CN III palsies in diabetic or hypertensive patients are more likely ischemic (microvascular, sparing the outer pupillomotor fibers).',
reference:'BCSC Section 5'},

{id:'ne03',subject:'neuro',difficulty:'hard',
stem:'Horner syndrome includes which triad of findings?',
options:['A. Ptosis, miosis, anhidrosis (and reverse ptosis)','B. Ptosis, mydriasis, cycloplegia','C. Proptosis, ptosis, and ophthalmoplegia','D. Ptosis, miosis, and ophthalmoplegia','E. Miosis, cycloplegia, and brow ptosis'],
correct:'A',
explanation:'Horner syndrome (oculosympathetic paresis) triad: (1) Ptosis (2-3 mm, due to loss of Muller muscle); (2) Miosis (pupil 1-2 mm smaller, more apparent in dim light); (3) Anhidrosis (ipsilateral face, if lesion is pre-ganglionic); (4) Reverse ptosis (lower lid elevation — "upside down ptosis" from inferior tarsal muscle denervation). No cycloplegia or ophthalmoplegia (those are CN III).',
reference:'BCSC Section 5'},

{id:'ne04',subject:'neuro',difficulty:'medium',
stem:'Papilledema (bilateral disc edema from raised intracranial pressure) is distinguished from pseudopapilledema by:',
options:['A. Visual acuity is typically worse in papilledema','B. Spontaneous venous pulsations are preserved in papilledema','C. B-scan ultrasound shows optic nerve sheath dilation in papilledema','D. Fluorescein angiography shows disc leakage only in pseudopapilledema','E. Visual field testing is not useful in papilledema'],
correct:'C',
explanation:'B-scan ultrasound: in papilledema, the optic nerve sheath is distended by CSF (greater than 3 mm sheath width 3 mm behind the globe = positive "30-degree test"). FA: papilledema shows disc leakage/blurring of disc margins with staining; drusen (pseudopapilledema) may autofluoresce. SVP: if present, SVP argues against elevated ICP, but SVP is absent in 20% of normals. Acuity is often preserved in early papilledema.',
reference:'BCSC Section 5'},

{id:'ne05',subject:'neuro',difficulty:'hard',
stem:'The "one-and-a-half syndrome" results from a lesion in:',
options:['A. Bilateral CN VI nuclei','B. The ipsilateral CN III nucleus and MLF','C. The ipsilateral PPRF and ipsilateral MLF (or CN VI nucleus and MLF)','D. The contralateral PPRF only','E. The ipsilateral cerebellum'],
correct:'C',
explanation:'"One-and-a-half syndrome" = ipsilateral conjugate gaze palsy (the "one") + ipsilateral internuclear ophthalmoplegia (the "half"). Result: the only remaining horizontal movement is abduction of the contralateral eye (with nystagmus). Caused by a lesion at/near the ipsilateral PPRF (or CN VI nucleus — for the conjugate gaze) and the ipsilateral MLF (for the INO component). Classic cause: MS or pontine infarction.',
reference:'BCSC Section 5'},

// ── UVEITIS ───────────────────────────────────────────────────────────────────
{id:'uv01',subject:'uveitis',difficulty:'easy',
stem:'A 28-year-old HLA-B27-positive male with ankylosing spondylitis develops acute onset of unilateral eye pain, photophobia, and a hypopyon. The MOST likely diagnosis is:',
options:['A. Posterior uveitis','B. Anterior uveitis (iritis/iridocyclitis)','C. Behcet disease','D. Sarcoidosis','E. Toxoplasma retinochoroiditis'],
correct:'B',
explanation:'HLA-B27-associated uveitis is the classic cause of acute anterior uveitis. Features: acute onset, unilateral (alternating attacks), severe photophobia/pain, significant fibrin/hypopyon, and association with seronegative spondyloarthropathies (AS, Reiter syndrome, IBD-associated, psoriatic arthritis). Treatment: intensive topical steroids and cycloplegics. Behcet can also cause hypopyon uveitis but is HLA-B51 and typically bilateral with other systemic features.',
reference:'BCSC Section 9'},

{id:'uv02',subject:'uveitis',difficulty:'medium',
stem:'The "headlight in the fog" appearance on fundus exam describes:',
options:['A. Active toxoplasma retinochoroiditis adjacent to an old scar','B. Acute retinal necrosis (ARN)','C. Cytomegalovirus (CMV) retinitis in an immunocompromised patient','D. Birdshot chorioretinopathy','E. Presumed ocular histoplasmosis syndrome (POHS)'],
correct:'A',
explanation:'"Headlight in the fog" describes a white, fluffy active toxoplasma lesion adjacent to a pigmented, punched-out old chorioretinal scar — the active lesion (headlight) surrounded by overlying vitritis (the fog). Toxoplasma gondii is the most common cause of posterior uveitis worldwide. The active lesion arises from cyst reactivation at the edge of an old scar.',
reference:'BCSC Section 9'},

{id:'uv03',subject:'uveitis',difficulty:'hard',
stem:'Sympathetic ophthalmia (SO) is a bilateral granulomatous uveitis that occurs after:',
options:['A. Autoimmune attack triggered by viral uveitis in one eye','B. Penetrating trauma or surgery to one eye, with subsequent uveal tissue sensitization','C. Systemic sarcoidosis with bilateral ocular involvement','D. Herpes zoster affecting both CN V divisions simultaneously','E. Behcet disease with bilateral ocular inflammation'],
correct:'B',
explanation:'Sympathetic ophthalmia is a rare (less than 0.3% after penetrating trauma) bilateral granulomatous panuveitis that develops in the uninjured (sympathizing) eye weeks to months after penetrating injury or surgery to the other (exciting) eye. Proposed mechanism: T-cell sensitization to uveal antigens (melanin-associated antigens). Treatment: systemic immunosuppression (high-dose steroids, steroid-sparing agents). Enucleation of the exciting eye within 2 weeks of injury may prevent SO.',
reference:'BCSC Section 9'},

{id:'uv04',subject:'uveitis',difficulty:'medium',
stem:'Sarcoid uveitis MOST commonly presents as:',
options:['A. Acute anterior uveitis','B. Chronic granulomatous anterior uveitis with mutton-fat keratic precipitates','C. Acute posterior uveitis with exudative detachment','D. Vitritis only without anterior segment involvement','E. Isolated optic nerve granuloma'],
correct:'B',
explanation:'Ocular sarcoidosis most commonly causes chronic, bilateral, granulomatous anterior uveitis with large "mutton-fat" keratic precipitates (KPs), iris nodules (Koeppe at pupillary margin, Busacca in stroma), and posterior synechiae. It may also cause intermediate uveitis (snowballs/snowbanking), periphlebitis ("candle wax drippings"), optic disc granulomas. Workup: ACE level, lysozyme, chest CT/X-ray.',
reference:'BCSC Section 9'},

// ── BASIC SCIENCE & ANATOMY ───────────────────────────────────────────────────
{id:'bs01',subject:'basic',difficulty:'medium',
stem:'The fovea centralis has the highest density of which photoreceptors?',
options:['A. Rods only','B. Both rods and cones equally','C. Cones only (no rods in the foveal center)','D. Rods in the center, cones in the parafovea','E. Intrinsically photosensitive retinal ganglion cells'],
correct:'C',
explanation:'The fovea centralis (specifically the foveola, ~350 um central zone) contains exclusively cone photoreceptors — there are NO rods in the central foveola. The rods begin at the edge of the fovea (~1 degree from fixation) and peak in density at ~20 degrees eccentricity (nasal to fovea). This is why rod-mediated (scotopic) vision is best with averted (eccentric) gaze — "off-axis fixation."',
reference:'BCSC Section 2'},

{id:'bs02',subject:'basic',difficulty:'easy',
stem:'The blood-retinal barrier (BRB) consists of:',
options:['A. Tight junctions between retinal pigment epithelial cells and between retinal vascular endothelial cells','B. The internal limiting membrane and Bruch\'s membrane','C. The ganglion cell layer and the RPE','D. Tight junctions only at the retinal capillaries','E. The vitreous base and zonular fibers'],
correct:'A',
explanation:'The blood-retinal barrier has two components: (1) OUTER BRB: tight junctions (zonulae occludens) between RPE cells, preventing diffusion from choriocapillaris into outer retina; (2) INNER BRB: tight junctions between retinal vascular endothelial cells, preventing intravascular contents from entering the inner retina. Breakdown of either component leads to retinal edema.',
reference:'BCSC Section 2'},

{id:'bs03',subject:'basic',difficulty:'hard',
stem:'The visual cycle (phototransduction) ends with the regeneration of 11-cis-retinal. Where does this regeneration primarily occur?',
options:['A. In the photoreceptor outer segment itself','B. In the retinal pigment epithelium (RPE)','C. In the Muller cells for cone photoreceptors','D. In the interphotoreceptor matrix','E. In the inner segments of photoreceptors'],
correct:'B',
explanation:'After photoisomerization, all-trans-retinal is released from opsin, reduced to all-trans-retinol (vitamin A) in the outer segment, transported to the RPE, and re-isomerized to 11-cis-retinol then oxidized to 11-cis-retinal, then returned to the photoreceptor for regeneration of rhodopsin. This "visual cycle" or "retinoid cycle" requires RPE65 (a key isomerase). Cone photoreceptors can also use an alternative Muller cell pathway for faster regeneration.',
reference:'BCSC Section 2'},

{id:'bs04',subject:'basic',difficulty:'medium',
stem:'The ciliary body produces aqueous humor. Which of the following CORRECTLY describes aqueous outflow?',
options:['A. 90% uveoscleral, 10% trabecular','B. 80-90% trabecular (conventional), 10-20% uveoscleral (unconventional)','C. 50% trabecular, 50% uveoscleral','D. 100% through the trabecular meshwork','E. 80% through Schlemm\'s canal directly, 20% trabecular'],
correct:'B',
explanation:'Conventional (trabecular) outflow: ~80-90% of aqueous drains through the trabecular meshwork → Schlemm\'s canal → collector channels → episcleral veins. Unconventional (uveoscleral) outflow: ~10-20% flows through the ciliary muscle interstitium → suprachoroidal space → sclera. Prostaglandin analogues (latanoprost, etc.) primarily increase UVEOSCLERAL outflow. Beta-blockers reduce aqueous production.',
reference:'BCSC Section 2'},

{id:'bs05',subject:'basic',difficulty:'easy',
stem:'The cranial nerve responsible for the corneal blink reflex (afferent limb) is:',
options:['A. CN II (optic nerve)','B. CN V1 (ophthalmic division of trigeminal)','C. CN VII (facial nerve)','D. CN III (oculomotor nerve)','E. CN VI (abducens nerve)'],
correct:'B',
explanation:'The corneal blink reflex: AFFERENT = nasociliary branch of V1 (CN V ophthalmic division) carrying sensation from the cornea; EFFERENT = CN VII (facial nerve) causing orbicularis oculi contraction → eye closure. Testing: touch cornea → both eyes should blink (direct and consensual). Loss of afferent (V1 lesion): no blink in either eye when that cornea is touched. Loss of efferent (CN VII palsy): no blink in the ipsilateral eye regardless of which cornea is stimulated.',
reference:'BCSC Section 2'},

{id:'bs06',subject:'basic',difficulty:'medium',
stem:'Optical coherence tomography (OCT) of the macula uses which principle?',
options:['A. Ultrasound with B-scan technology at 20 MHz','B. Low-coherence interferometry with near-infrared light','C. Confocal scanning laser ophthalmoscopy','D. Scanning laser polarimetry','E. Scanning laser doppler flowmetry'],
correct:'B',
explanation:'OCT uses low-coherence interferometry: a near-infrared light beam (~840 nm for time-domain; ~1060 nm for long-wavelength) is split — one beam goes to the tissue, one to a reference mirror. Backscattered light from the tissue interferes with the reference beam; the interference pattern encodes depth information. Spectral-domain OCT measures all depths simultaneously via Fourier transform, giving axial resolution ~5-7 um.',
reference:'BCSC Section 2'},

{id:'bs07',subject:'basic',difficulty:'hard',
stem:'Which cytokine is the PRIMARY driver of corneal neovascularization?',
options:['A. IL-1 beta','B. VEGF-A (vascular endothelial growth factor A)','C. TNF-alpha','D. TGF-beta','E. IL-17'],
correct:'B',
explanation:'VEGF-A (specifically isoforms VEGF-A165 and VEGF-A121) is the primary angiogenic factor driving new vessel growth, including corneal neovascularization, retinal neovascularization in PDR/ROP, and choroidal neovascularization in AMD. VEGF binds VEGFR-1 and VEGFR-2 on endothelial cells, driving proliferation, migration, and survival. This is the target of anti-VEGF drugs (bevacizumab, ranibizumab, aflibercept). IL-1 beta plays a role in corneal inflammation and NV but is not the primary driver.',
reference:'BCSC Section 2/8'},
];
